### ISSUE TITLE
Passing tests on travis

### ISSUE THREAD

**Issue by jamen** [audiojs/contributing#13]
Right now most of the tests don't pass on Travis.  Here are the statuses: https://travis-ci.org/audiojs

**Comment by jamen** [comment]
looks like i might have done the configs wrong on a few?  some say ruby.

**Comment by dfcreative** [comment]
Interesting what is due way to assert results. Too precise comparison is no good, due to different delays, glitches etc. But too loose neither, in case if channels swapped or noise instead of a sine appeared.

Maybe using loose spectrum estimation would work, with [fourier-transform](https://github.com/scijs/fourier-transform). Or even better - detect N spectral peaks and use [almost-equal](https://www.npmjs.com/package/almost-equal) for magnitudes/frequencies comparison.

Should think about _audio-fft_ component, to convert audio data to frequencies data, maybe.
