### ISSUE TITLE
Repo style questions

### ISSUE THREAD

**Issue by jamen** [audiojs/contributing#35]
I have some questions for the style of the repos we could establish further here to clean up any inconsistencies

1. Should we push [`yarn.lock`](https://yarnpkg.com/lang/en/docs/yarn-lock/) or should it be inside `.gitignore`?
   - Helpful when someone  clones the repo and uses the lockfile to download the deps
   - More consistent installs between collaborators [and Travis CI](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), and other benefits of a lockfile
   - Not helpful when published, so it should be npm ignored (see below)
1. Should we use `.npmignore` or `"files"`?
   - I personally prefer files option and less dotfiles in general
   - npmignore has a "more safe" mechanism by being opt-out, so you are more unlikely to accidentally publish with missing files (unless there is a tool out there that checks for you?)
1. How should files be cased? `README` vs `readme`, `LICENSE` vs `license`, etc.
1.  Should we have one readme style across the board?  Possibly with a template scaffolding and/or tool (e.g. [`yo`](https://npmjs.com/yo), [`generate`](https://npmjs.com/generate), or [`bp`](https://github.com/jamen/bp) for simple stuff)
1. Should we more eagerly link back to some origin repository or page (like [audiojs.github.io](https://audiojs.github.io) or [github.com/audiojs/audio](https://github.com/audiojs/audio), etc.) near the title area, to tie everything back together nicely.  Another method people seem to take is [monorepos](https://github.com/lerna/lerna), but that might deviate too far from the style we have established and I'm not sure about them myself yet.
1. How should we organize different clusters of packages with npm keywords, `audiojs/docs`, and so on.  For example: `pull-audio-*` packages can be categorized by a `pull-audio` keyword, and `cli` packages by `audio-cli`, etc. but you also have groups going the other direction like `audio-gain` and it having `pull`, `stream`, and `cli`  packages

**Comment by dfcreative** [comment]
1. :+1:, although I'm off the yarn manager
2. There's been lot of hassle about broken "files" option in npm, so def `.npmignore`
3. :+1: for lowercase with extension, ie `readme.md`, `license.md`
4. I would go for minimally required ecosystem badges like _build_, _stability_ and _greenkeeper_, and basic sections _usage_ and _api_, the later is optional if the module is self-explanatory. The rest is up to author, optionally _table of content_, _credits_, _related_, other badges, contributors, donate bitcoins etc.
5. :+1:  for that, mb we can do sweet @audiojs badge, like ![](https://camo.githubusercontent.com/dee0c8fe254d0b8b704bb9f1eff6431a73c1f9d4/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f73696d706c792d617765736f6d652d627269676874677265656e2e737667) [here](https://github.com/mapbox/supercluster). That also enhances ux/seo.
6. I'd go for removing bad tags and leaving only ecosystem ones: pull-stream, audiojs, stream, cli etc. Because that drops our reputation when someone types `dsp` or `fft` in npm search and sees unrelated audio-* packages like audio-shader or audio-through.

**Comment by jamen** [comment]
With npm 5 out, we should use `package-lock.json` instead of `yarn.lock`

**Comment by jamen** [comment]
New opinion about lockfiles:  Maybe we should keep them ignored?
 - It can be distracting inside git diff
 - Not _that_ useful for small libraries
 - Makes the developers depend on lockfile while the users are depending on package.json fields.

**Comment by dfcreative** [comment]
Agreed 100% :) Tbh npm@5 was a pain for me with all the installing trickery, switched back to v4
